### PR TITLE
Dependencies and README update

### PR DESCRIPTION
**Pull request by fcatalan92**
I updated the dependencies to the latest versions. I added also pylint, flake8 and pytest as extra dependencies for the development mode, asking the most up to date version since the CI use the latest releases.
@mconcas What do you think? Should we pin the package version in the CI?

### CODE REVIEW

**Comment by mpuccio** [comment]
I would not pin the versions, in this way if some new version breaks our code we can fix it timely (or then fix the package version in our dependency tree)

**Comment by mconcas** [comment]
> I updated the dependencies to the latest versions. I added also pylint, flake8 and pytest as extra dependencies for the development mode, asking the most up to date version since the CI use the latest releases.
> @mconcas What do you think? Should we pin the package version in the CI?

CI runs only once. If the possibly breaking package is released later, you will have an inconsistent state for the published version.
I have no clue how often this could happen and how critical can be, be just ready.

**Comment by mconcas** [comment]
We can just opt in favour of `>=`, to reduce actions on user's side when possible updates.

**Comment by fcatalan92** [comment]
I checked some other projects and some [documentation](https://packaging.python.org/discussions/install-requires-vs-requirements/). It looks like asking ```>=``` is still quite strong, however I think we can try this and see if it fits.

**Pull request merged**
