### PR TITLE
Return TreeHandlers for not inplace operations

### PR DESCRIPTION
**Pull request by fmazzasc**
This P.R. solves #82 . 
@fcatalan92 what do you think? Since some improvements have been done since the last release I think it's time to bump a new one

### CODE REVIEW

**Comment by fcatalan92** [comment]
Hi @fmazzasc, very nice! Is there a way to avoid disabling pylint? Maybe you can also add some tests to check this new functionality.

We can release 0.0.7 after #80 I think, we won't wait for shap as @mpuccio  suggested.

**Comment by fmazzasc** [comment]
Hi @fcatalan92 , 
I haven't found a smart way to avoid disabling pylint for our use case. Do you have any idea on how to do that? However I have implemented some tests for the new functionalities

**Comment by fcatalan92** [comment]
> I haven't found a smart way to avoid disabling pylint for our use case. Do you have any idea on how to do that?
I haven't found any good solution neither. I think it's fine as it is.

**Comment by fmazzasc** [comment]
I think It is useful to access to the columns of the dataframe using a dictionary-like syntax. I have also redefined the `len` operator with the same logic. @fcatalan92 What do you think ?

**Comment by fcatalan92** [comment]
Hi @fmazzasc, I think that it is a nice idea! Maybe add some comments because this works only on the full dataframe and it's better to point it out in my opinion.

**Comment by fmazzasc** [comment]
@fcatalan92 done! Thanks

**Pull request merged**
