### PR TITLE
Add tutorial for binary classification

### PR DESCRIPTION
**Pull request by lbariogl**

### CODE REVIEW

**Comment by mconcas** [comment]
Link is set to point to future merged PR.
To test it use this direct link:

https://colab.research.google.com/github/lbariogl/hipe4ml/blob/master/tutorials/hipe4ml_tutorial_binary.ipynb

**Comment by fmazzasc** [comment]
Ciao Luca, 
thanks for the very nice tutorial. I have just a couple of comments:

- In the section `Bayesian optimisation of hyperparameters`  I think that you should mention that the ModelHandler automatically updates its hyperparameters at the end of the optimisation process. If you don't specify It the user could be a bit confused about which hyperparameter values are used for the training in the following section.

- The variable ` train_test_data` is used in the section `Bayesian optimisation of hyperparameters` before its definition in the `Training and testing the model` section. A good check that you can do to avoid this kind of issue is to restart the notebook and run It from scratch sequentially.

Thanks again for the hard work!
Francesco

**Comment by lbariogl** [comment]
Hi guys,
thank you for your comments. I have implemented them and now everything should be fine.

**Comment by fmazzasc** [comment]
Thanks @lbariogl !

**Pull request merged**
