### PR TITLE
Rework of ROC metric and curves in multi-classification

### PR DESCRIPTION
**Pull request by fcatalan92**
This PR reworks ROC usage in the case of multi-classification. I tried to use scikit-learn [roc_auc_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score) as much as possible. The extension of the ROC metric to the multi-class case has some nuances (see [here](https://github.com/scikit-learn/scikit-learn/pull/7663#issuecomment-327544404) and [here](https://github.com/scikit-learn/scikit-learn/pull/7663#issuecomment-307566895)), so I decided to stick with the scikit-learn approach that is based on published articles.

I also added a `multiclass` flag to the ModelHandler data members and cleaned the docstrings.

### CODE REVIEW

**Comment by fmazzasc** [comment]
Hi @fcatalan92 , thanks for the hard work! I have just a comment: since you've added the multiclass flag to the ModelHandler object you should also update the `load_model_handler` method allowing to load this new flag in the empty ModelHandler.
Ciao,
Francesco

**Comment by fcatalan92** [comment]
Hi @fmazzasc, I missed it. Now should be fixed, thank you!

**Comment by fcatalan92** [comment]
> I only have a small concern about the "multiclass" flag. Is it really needed? Or can it be inferred from the input data as done here
> 
> https://github.com/hipe4ml/hipe4ml/blob/d2d01b483bed01910694d8ef82de0a1271f0ba69/hipe4ml/model_handler.py#L204
> ? If possible I would avoid the explicit flag, so that the user can also not care about it. If instead is needed, it's ok for me to have it.

At the moment only the predict() method use it, I can try to infer the number of classed also in that case.

**Comment by fgrosa** [comment]
> > I only have a small concern about the "multiclass" flag. Is it really needed? Or can it be inferred from the input data as done here
> > https://github.com/hipe4ml/hipe4ml/blob/d2d01b483bed01910694d8ef82de0a1271f0ba69/hipe4ml/model_handler.py#L204
> > 
> > ? If possible I would avoid the explicit flag, so that the user can also not care about it. If instead is needed, it's ok for me to have it.
> 
> At the moment only the predict() method use it, I can try to infer the number of classes also in that case.

If it is not too complex I would do it, thanks a lot!

**Comment by fcatalan92** [comment]
@fgrosa This solution should work. @fmazzasc could you run this on a binary problem, just to be shure that everything is fine.

**Comment by fmazzasc** [comment]
@fcatalan92  I tried to run the example code: `training_and_testing_example.py` . It fails with the following error message:
```
  File "training_and_testing_example.py", line 41, in <module>
    MODEL.train_test_model(DATA)
  File "/home/francesco/hipe4ml/hipe4ml/model_handler.py", line 205, in train_test_model
    roc_score = roc_auc_score(data[3], y_pred, average=average, multi_class=multi_class_opt)
TypeError: roc_auc_score() got an unexpected keyword argument 'multi_class'
```

**Comment by fcatalan92** [comment]
Hi @fmazzasc, you should update scikit-learn at the latest version (the multi-class ROC AUC was added in the last release). Just do `pip3 install -e .[dev]`, the dependency should be updated.
Nevertheless, I forgot that there was the example that can be run. It works on my machine.

**Comment by fmazzasc** [comment]
thanks @fcatalan92 , everything works fine for me!

**Comment by fgrosa** [comment]
Great! As last thing @fcatalan92 could you bump the version so that we then do a new realease? Thanks!

**Pull request merged**
